// na6-solid/src/components/Menu.tsx
import { Link } from "solid-app-router";
import { Component } from "solid-js";
import { naukowiec } from "../dane";

export const Menu: Component<{ dane: Array<naukowiec> }> = ({ dane }) => {
    return (
        <ul class="nav flex-column">
            {/* mapuje dane zamiast używania komponentu For, ponieważ dane nie są reaktywne */}
            {dane.map((osoba) => {
                return (
                    <li class="nav-item">
                        <Link class="nav-link" href={`/${osoba.id}`}>
                            {osoba.nazwisko}
                        </Link>
                    </li>
                );
            })}
        </ul>
    );
};

// na6-react/src/components/Menu.tsx
import React from "react";
import { Nav, NavItem } from "react-bootstrap";
import { Link } from "react-router-dom";
import { naukowiec } from "../dane";

export const Menu: React.FC<{ dane: Array<naukowiec> }> = ({ dane }) => {
    return (
        <Nav className="flex-column">
            {dane.map((osoba) => {
                return (
                    <NavItem key={osoba.id}>
                        <Nav.Link as={Link} to={`/${osoba.id}`}>
                            {osoba.nazwisko}
                        </Nav.Link>
                    </NavItem>
                );
            })}
        </Nav>
    );
};
