// na6-react/src/main.tsx
import "bootstrap/dist/css/bootstrap.min.css";
import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import App from "./App";

ReactDOM.createRoot(document.getElementById("root")!).render(
    <BrowserRouter>
        <App />
    </BrowserRouter>
);

// na6-solid/src/index.tsx
/* @refresh reload */
import "bootstrap/scss/bootstrap.scss";
import "bootstrap-icons/font/bootstrap-icons.scss";
import "bootstrap/dist/js/bootstrap.bundle.min.js";
import "./index.scss";
import { render } from "solid-js/web";
import { Router } from "solid-app-router";
import App from "./App";

render(
    () => (
        <Router>
            <App />
        </Router>
    ),
    document.getElementById("root") as HTMLElement
);
