// na6-react/src/components/Layout.tsx
import { FC } from "react";
import { Footer } from "./Footer";
import { ZmianaKoloru } from "./ZmianaTla";

export const Layout: FC<{ children: JSX.Element; header: string }> = ({
    children,
    header,
}) => {
    return (
        <>
            <header className="bg-secondary text-white ">
                <h1 className="container display-3">{header}</h1>
            </header>
            <ZmianaKoloru />
            {children}
            <Footer />
        </>
    );
};

// na6-solid/src/components/Layout.tsx
import { Component, JSXElement } from "solid-js";
import { Footer } from "./Footer";
import { ZmianaTla } from "./ZmianaTla";
export const Layout: Component<{ children: JSXElement; header: string }> = ({
    children,
    header,
}) => {
    return (
        <>
            <header class="bg-secondary text-white ">
                <h1 class="container display-3">{header}</h1>
            </header>
            <ZmianaTla />
            {children}
            <Footer />
        </>
    );
};
