// na6-solid/src/App.tsx
import { Route, Routes } from "solid-app-router";
import type { Component } from "solid-js";
import { StronaGlowna } from "./components/StronaGlowna";
import { Naukowiec } from "./components/naukowiec/Naukowiec";

const App: Component = () => {
    return (
        <div class="App d-flex flex-column">
            <Routes>
                <Route path="/" element={<StronaGlowna />} />
                <Route path="/:id" element={<Naukowiec />} />
            </Routes>
        </div>
    );
};

export default App;

// na6-react/src/App.tsx
import { Route, Routes } from "react-router-dom";
import { Footer } from "./components/Footer";
import { Naukowiec } from "./components/Naukowiec/Naukowiec";
import { StronaGlowna } from "./components/StronaGlowna";

function App() {
    return (
        <div className="App d-flex flex-column">
            <Routes>
                <Route path="/" element={<StronaGlowna />} />
                <Route path="/:id" element={<Naukowiec />} />
            </Routes>

            <Footer />
        </div>
    );
}

export default App;
